stages:
  - test
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""

test:
  stage: test
  image: python:3.9-slim
  script:
    - pip install -r requirements.txt
    - pytest ./tests
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker info
  script:
    - docker build -t snake-app .
    - docker tag snake-app $CI_REGISTRY_IMAGE:latest
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:latest
  tags:
    - docker

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker info
  script:
    - ssh -i $SSH_PRIVATE_KEY ubuntuuser@81.94.155.54 "cd /snake-game && git pull origin main && docker-compose down && docker-compose up -d"
  tags:
    - docker
