sonar.projectKey=snake-game
sonar.projectName=Snake Game
sonar.sources=snake/
sonar.exclusions=**/__pycache__/**,**/*.pyc
sonar.tests=snake/tests
sonar.test.inclusions=**/test_*.py
sonar.sourceEncoding=UTF-8
