apiVersion: v1
kind: Namespace
metadata:
  name: falco
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: falco
  namespace: falco
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: falco-config
  namespace: falco
data:
  falco.yaml: |
    rules_file:
      - /etc/falco/rules.d
    plugins:
      - name: json
        library_path: libjson.so
        init_config: ""
    buffered_outputs: false
    time_format_iso_8601: true
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: falco
  namespace: falco
spec:
  selector:
    matchLabels:
      app: falco
  template:
    metadata:
      labels:
        app: falco
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      serviceAccountName: falco
      dnsPolicy: ClusterFirstWithHostNet
      
      containers:
      - name: falco
        image: falcosecurity/falco:latest
        imagePullPolicy: IfNotPresent
        
        securityContext:
          privileged: true
        
        volumeMounts:
        - name: docker-sock
          mountPath: /var/run/docker.sock
        - name: sys
          mountPath: /sys
        - name: lib-modules
          mountPath: /lib/modules
        - name: usr
          mountPath: /usr
        - name: etc
          mountPath: /etc
        - name: falco-config
          mountPath: /etc/falco
      
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
      - name: sys
        hostPath:
          path: /sys
      - name: lib-modules
        hostPath:
          path: /lib/modules
      - name: usr
        hostPath:
          path: /usr
      - name: etc
        hostPath:
          path: /etc
      - name: falco-config
        configMap:
          name: falco-config
