apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: snake-game-monitor
  namespace: app-production
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: snake-game
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
    port: http
